MD013:
  line_length: 140
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
MD033: false
MD041:
  allow_preamble: true
